// app/legal/report-ownership/page.tsx
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Report Ownership & Usage Policy | Old Crows Wireless Solutions LLC",
  description:
    "Who owns Corvus reports and Crow's Eye outputs, what you can do with them, and what Old Crows Wireless Solutions LLC retains.",
};

export default function ReportOwnershipPage() {
  return (
    <main style={{ background: "#0D1520", minHeight: "100vh" }}>
      <section className="ocws-container py-16">

        {/* Header */}
        <div className="mb-12">
          <p className="text-xs font-semibold uppercase tracking-widest mb-3" style={{ color: "#00C2C7", letterSpacing: "0.18em" }}>
            Legal &middot; Old Crows Wireless Solutions LLC
          </p>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Report Ownership &amp; Usage Policy
          </h1>
          <p className="text-base" style={{ color: "#888" }}>
            Effective date: March 23, 2026 &middot; Applies to Corvus reports, Crow&rsquo;s Eye outputs, and all deliverables produced by Old Crows Wireless Solutions LLC
          </p>
        </div>

        <div className="space-y-6">

          {/* Overview */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">Overview</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: "#aaa" }}>
              When you pay for a Corvus Verdict, Reckoning, or other report deliverable from Old Crows Wireless Solutions LLC, you receive ownership of that specific output document. You do not receive ownership of the platform, methodology, scoring systems, or intellectual property that produced it.
            </p>
            <p className="text-sm leading-relaxed" style={{ color: "#aaa" }}>
              This policy clarifies what &ldquo;ownership&rdquo; means for OCWS-produced outputs, how you may use them, and what OCWS retains in all cases. It applies to all deliverables produced by Corvus, Crow&rsquo;s Eye, and all services of Old Crows Wireless Solutions LLC, including but not limited to Verdicts, Reckonings, monitoring summaries, and Pro Certified reports.
            </p>
          </div>

          {/* What You Own */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">What You Own</h2>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <p>
                Upon payment and delivery, you own the <strong className="text-white">specific output document</strong> produced for your submission. This includes:
              </p>
              <ul className="space-y-2 ml-4">
                {[
                  "The Verdict PDF or digital report generated for your specific scan data",
                  "The Reckoning PDF or digital report generated for your specific facility data",
                  "The Pro Certified Reckoning report signed and certified by Joshua Turner",
                  "Any monitoring summary or output generated by Crow's Eye for your specific submissions",
                  "Any OCWS Pro on-site assessment report delivered to you",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span style={{ color: "#00C2C7", flexShrink: 0 }}>✓</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-2">
                You own the document. You do not own the methodology, the analysis engine, the scoring system, or any component of the platform that produced it.
              </p>
            </div>
          </div>

          {/* Permitted Uses */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">Permitted Uses</h2>
            <p className="text-sm mb-4" style={{ color: "#aaa" }}>You may use your OCWS report or output for the following purposes:</p>
            <ul className="space-y-2 text-sm" style={{ color: "#aaa" }}>
              {[
                "Personal use — implementing recommendations at your own property",
                "Internal business use — sharing with employees, IT staff, or facilities personnel within your organization",
                "Client delivery — presenting findings to your clients as part of your own professional services (Flock and Murder tier subscribers with white-label rights)",
                "Vendor communication — sharing with equipment vendors, ISPs, or contractors for implementation purposes",
                "Insurance and compliance documentation — presenting a Pro Certified Reckoning to insurers, regulators, or compliance reviewers for its stated purpose",
                "Board or executive presentations — presenting findings to internal stakeholders",
                "Legal proceedings — using a Pro Certified Reckoning as supporting documentation in a legal matter, with appropriate attribution to OCWS",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span style={{ color: "#00C2C7", flexShrink: 0 }}>✓</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <div className="mt-4 rounded-xl p-4 text-sm" style={{ background: "rgba(0,194,199,0.06)", border: "1px solid rgba(0,194,199,0.2)" }}>
              <p style={{ color: "#aaa" }}>
                <strong className="text-white">White-label note:</strong> Flock and Murder tier subscribers with white-label PDF rights may present Corvus reports under their own branding when delivering them to clients. The underlying OCWS methodology and report structure remain OCWS intellectual property. Misrepresenting the source of the analysis or passing it off as your own proprietary technology is not permitted.
              </p>
            </div>
          </div>

          {/* Restrictions */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">Restrictions</h2>
            <p className="text-sm mb-4" style={{ color: "#aaa" }}>You may not use OCWS reports or outputs for the following without prior written consent from OCWS:</p>
            <ul className="space-y-2 text-sm" style={{ color: "#aaa" }}>
              {[
                "Reselling reports as standalone products to third parties",
                "Publishing reports publicly in a manner that implies OCWS endorsement of a commercial product or service",
                "Using reports to train, fine-tune, or evaluate any AI or machine learning model",
                "Reproducing OCWS scoring logic, methodology, or analytical structure in a competing product or service",
                "Modifying reports in a way that misrepresents OCWS findings or creates a false impression of findings",
                "Using a Pro Certified Reckoning in a context for which it was not certified, or misrepresenting its scope or findings",
                "Distributing reports in bulk for purposes unrelated to the facility or site analyzed",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span style={{ color: "#888", flexShrink: 0 }}>✗</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* What OCWS Retains */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">What Old Crows Wireless Solutions LLC Retains</h2>
            <p className="text-sm mb-4" style={{ color: "#aaa" }}>
              Regardless of what you purchase, Old Crows Wireless Solutions LLC retains full ownership of:
            </p>
            <ul className="space-y-2 text-sm" style={{ color: "#aaa" }}>
              {[
                "All Corvus platform logic, algorithms, AI models, and analysis methodology",
                "All Crow's Eye monitoring systems, scan interpretation logic, and observational frameworks",
                "Report templates, scoring systems, severity classification systems, and finding structures",
                "The Corvus, Crow's Eye, The Full Reckoning, and Corvus' Verdict brands and unregistered trademarks",
                "All source code, infrastructure, and platform technology underlying OCWS products",
                "Aggregated, anonymized, and de-identified data derived from all customer submissions",
                "The certification methodology and professional standards applied in Pro Certified Reckoning engagements",
                "All OCWS training materials, documentation, and internal processes",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span style={{ color: "#B8922A", flexShrink: 0 }}>◆</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* Anonymized Data */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">Anonymized Data Usage</h2>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <p>
                Old Crows Wireless Solutions LLC may collect, retain, and use <strong className="text-white">anonymized and de-identified data</strong> derived from customer submissions to Corvus, Crow&rsquo;s Eye, and other OCWS services. This includes but is not limited to:
              </p>
              <ul className="space-y-2 ml-4">
                {[
                  "RF environment patterns and signal characteristics (stripped of personally identifiable location data)",
                  "Router vendor, firmware, and configuration patterns observable from scan data",
                  "Channel congestion and interference patterns aggregated across environments",
                  "Network count, density, and SSID structure patterns",
                  "Scan quality metrics and data submission patterns",
                  "Monitoring frequency and behavioral patterns from Crow's Eye usage",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span style={{ color: "#00C2C7", flexShrink: 0 }}>—</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p>
                This anonymized data may be used to improve Corvus analysis quality, train and refine OCWS models, develop new product features, produce industry research, or support OCWS business operations. <strong className="text-white">No personally identifiable information, address data, customer name, or account information is included in anonymized data sets.</strong>
              </p>
              <p>
                You may opt out of anonymized data usage by contacting OCWS. Opting out does not affect your access to OCWS Services or the quality of your individual outputs.
              </p>
            </div>
          </div>

          {/* Crow's Eye */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">Crow&rsquo;s Eye Monitoring Data</h2>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <p>
                Data submitted to Crow&rsquo;s Eye for monitoring, scanning, and observational purposes is treated under the same ownership framework as Corvus report data. Specifically:
              </p>
              <ul className="space-y-2 ml-4">
                {[
                  "You retain ownership of the specific outputs and monitoring summaries delivered to you",
                  "OCWS retains the monitoring platform, observational logic, and all associated intellectual property",
                  "Anonymized scan and monitoring patterns may be retained by OCWS as described above",
                  "Crow's Eye session data and raw submission files are not permanently stored beyond the period necessary to generate your output, except where required by law or explicitly agreed in an enterprise contract",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span style={{ color: "#00C2C7", flexShrink: 0 }}>—</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Attribution */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">Attribution</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: "#aaa" }}>
              When sharing a Corvus report or Crow&rsquo;s Eye output in a professional context, we encourage attribution to Old Crows Wireless Solutions LLC as the source of the analysis. Attribution is not required for internal use.
            </p>
            <p className="text-sm leading-relaxed" style={{ color: "#aaa" }}>
              Pro Certified Reckoning reports carry Joshua Turner&rsquo;s personal certification and must not be altered, excerpted, or presented in a way that misrepresents the scope of his certification. The report must be presented in its complete and unmodified form when used for compliance, insurance, or legal purposes.
            </p>
          </div>

          {/* Policy nav */}
          <div className="rounded-2xl p-6" style={{ background: "rgba(0,0,0,0.2)", border: "1px solid rgba(255,255,255,0.06)" }}>
            <p className="text-xs font-semibold uppercase tracking-widest mb-4" style={{ color: "#888" }}>Related Policies</p>
            <div className="flex flex-wrap gap-3">
              {[
                { href: "/legal/terms", label: "Terms of Service" },
                { href: "/legal/guarantee", label: "Guarantee Policy" },
                { href: "/legal/refunds", label: "Refund Policy" },
              ].map((l) => (
                <Link
                  key={l.href}
                  href={l.href}
                  className="inline-flex items-center rounded-xl px-4 py-2 text-sm font-semibold ocws-glow-hover"
                  style={{ border: "1px solid rgba(0,194,199,0.35)", color: "#00C2C7", background: "transparent" }}
                >
                  {l.label}
                </Link>
              ))}
            </div>
          </div>

        </div>
      </section>
    </main>
  );
}
