// app/legal/terms/page.tsx
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Old Crows Wireless Solutions LLC",
  description:
    "Terms of Service for Old Crows Wireless Solutions LLC, governing use of Corvus, Crow's Eye, and all related products and services.",
};

export default function TermsPage() {
  return (
    <main style={{ background: "#0D1520", minHeight: "100vh" }}>
      <section className="ocws-container py-16">

        {/* Header */}
        <div className="mb-12">
          <p className="text-xs font-semibold uppercase tracking-widest mb-3" style={{ color: "#00C2C7", letterSpacing: "0.18em" }}>
            Legal &middot; Old Crows Wireless Solutions LLC
          </p>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">
            Terms of Service
          </h1>
          <p className="text-base" style={{ color: "#888" }}>
            Effective date: March 23, 2026 &middot; Applies to all products and services provided by Old Crows Wireless Solutions LLC
          </p>
        </div>

        <div className="space-y-6">

          {/* 1. Agreement */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">1. Agreement to Terms</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: "#aaa" }}>
              These Terms of Service (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you (&ldquo;Customer,&rdquo; &ldquo;you,&rdquo; or &ldquo;user&rdquo;) and <strong className="text-white">Old Crows Wireless Solutions LLC</strong>, a Florida limited liability company (&ldquo;OCWS,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By accessing or using any product or service provided by OCWS, including but not limited to Corvus and Crow&rsquo;s Eye, you agree to be bound by these Terms.
            </p>
            <p className="text-sm leading-relaxed" style={{ color: "#aaa" }}>
              If you do not agree to these Terms, do not access or use our products or services. Continued use constitutes ongoing acceptance of these Terms as they may be updated from time to time.
            </p>
          </div>

          {/* 2. Definitions */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">2. Definitions</h2>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <div>
                <span className="text-white font-semibold">Old Crows Wireless Solutions LLC (&ldquo;OCWS&rdquo;)</span> — the Florida limited liability company that owns and operates the Corvus platform, Crow&rsquo;s Eye monitoring tool, and all associated services.
              </div>
              <div>
                <span className="text-white font-semibold">Corvus</span> — an unregistered trademark of OCWS and the AI-assisted RF analysis and report generation engine that produces Verdicts, Reckonings, and related diagnostic outputs. Corvus is a product of Old Crows Wireless Solutions LLC.
              </div>
              <div>
                <span className="text-white font-semibold">Crow&rsquo;s Eye</span> — an unregistered trademark of OCWS and the wireless monitoring, scanning, and observational platform through which customers submit data and receive Corvus outputs. Crow&rsquo;s Eye is a product of Old Crows Wireless Solutions LLC.
              </div>
              <div>
                <span className="text-white font-semibold">Verdict</span> — a single-location diagnostic report generated by Corvus based on customer-submitted scanner data.
              </div>
              <div>
                <span className="text-white font-semibold">Reckoning</span> — a multi-location diagnostic report generated by Corvus synthesizing data from multiple scan points within a site or facility.
              </div>
              <div>
                <span className="text-white font-semibold">Pro Certified Reckoning</span> — a premium service in which Joshua Turner personally reviews, certifies, and signs every finding in a Reckoning report.
              </div>
              <div>
                <span className="text-white font-semibold">Services</span> — all analytical, diagnostic, monitoring, advisory, reporting, and platform services provided by OCWS, including Corvus, Crow&rsquo;s Eye, on-site RF assessments, and any other current or future offerings.
              </div>
              <div>
                <span className="text-white font-semibold">Subscription</span> — a recurring billing arrangement (Nest, Flock, or Murder tier) granting the customer ongoing access to OCWS Services.
              </div>
            </div>
          </div>

          {/* 3. Services */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">3. Nature of Services</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: "#aaa" }}>
              Corvus, Crow&rsquo;s Eye, and other products or services provided by Old Crows Wireless Solutions LLC are <strong className="text-white">analytical, diagnostic, monitoring, and advisory</strong> in nature. All outputs — including Verdicts, Reckonings, reports, findings, recommendations, scores, and alerts — represent Corvus&rsquo;s analysis of the data provided by the customer and the observable conditions present at the time of analysis.
            </p>
            <p className="text-sm leading-relaxed mb-3" style={{ color: "#aaa" }}>
              OCWS Services are designed to provide clarity about RF environments and wireless network conditions. They do not constitute professional engineering certification, legal compliance documentation (except where explicitly described as such in a Pro Certified Reckoning), network management, ISP services, or hardware maintenance.
            </p>
            <p className="text-sm leading-relaxed" style={{ color: "#aaa" }}>
              The accuracy of all outputs depends on the quality, completeness, and accuracy of data submitted by the customer. OCWS is not responsible for errors or omissions in outputs resulting from incomplete, inaccurate, or misrepresented data submissions.
            </p>
          </div>

          {/* 4. Subscriptions and Billing */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">4. Subscriptions, Billing, and Overages</h2>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <p><strong className="text-white">Subscription Tiers.</strong> OCWS offers monthly and annual subscription plans (Nest, Flock, and Murder tiers) with defined allotments of Verdicts, Reckonings, and platform features. Plan details, pricing, and allotments are described at the time of enrollment and may be updated with reasonable notice.</p>
              <p><strong className="text-white">Minimum Commitments.</strong> Monthly subscription plans require a minimum three (3) month commitment. By enrolling in a monthly subscription, you authorize OCWS to charge the applicable monthly fee for a minimum of three months. After the minimum period, subscriptions continue month-to-month until cancelled.</p>
              <p><strong className="text-white">Annual Plans.</strong> Annual subscription plans are billed in full at the time of enrollment and have no minimum commitment period beyond the initial annual term. Annual plans may be cancelled for a prorated refund of unused months, subject to the Refund Policy.</p>
              <p><strong className="text-white">Overages.</strong> Usage beyond your plan&rsquo;s included allotments will be billed at the applicable overage rate for your tier. You are responsible for monitoring your usage and authorizing overage charges by continuing to use the Service beyond your allotment.</p>
              <p><strong className="text-white">Single Purchases.</strong> Verdicts, Reckonings, and credit packs may be purchased individually without a subscription at the rates published at the time of purchase.</p>
              <p><strong className="text-white">Billing Errors.</strong> If you believe a billing error has occurred, you must notify OCWS within 30 days of the charge. OCWS will investigate and, if an error is confirmed, issue a correction or credit.</p>
            </div>
          </div>

          {/* 5. No Guarantees */}
          <div
            className="rounded-2xl p-8"
            style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}
          >
            <h2 className="text-xl font-bold text-white mb-2">5. No Guarantees; Disclaimers</h2>
            <p className="text-xs font-semibold uppercase tracking-widest mb-4" style={{ color: "#00C2C7" }}>
              Important — please read carefully
            </p>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <p>
                <strong className="text-white">No Performance Guarantee.</strong> Corvus, Crow&rsquo;s Eye, and other products or services provided by Old Crows Wireless Solutions LLC do not guarantee any improvement in Wi-Fi performance, network speed, signal strength, coverage, or connectivity outcomes. All findings and recommendations are based on analysis of submitted data and observable RF conditions at the time of analysis.
              </p>
              <p>
                <strong className="text-white">No Interference Elimination Guarantee.</strong> OCWS does not guarantee the elimination of RF interference, channel congestion, signal degradation, or any other wireless network issue identified in a Verdict or Reckoning. Recommendations are advisory. Implementation and results depend on factors outside OCWS&rsquo;s control, including but not limited to hardware capabilities, ISP constraints, building materials, neighboring networks, and customer actions.
              </p>
              <p>
                <strong className="text-white">No Security Outcome Guarantee.</strong> Findings related to network security posture — including open networks, encryption gaps, or unauthorized access points — are advisory only. OCWS does not guarantee that implementing security recommendations will prevent unauthorized access, data breaches, or other security incidents.
              </p>
              <p>
                <strong className="text-white">No Monitoring Accuracy Guarantee.</strong> Crow&rsquo;s Eye monitoring and scanning functions provide observational data based on what is detectable and visible in the RF environment at the time of scanning. OCWS does not guarantee continuous, complete, or real-time accuracy of monitoring outputs, and is not responsible for changes in the RF environment that occur between scans or monitoring intervals.
              </p>
              <p>
                <strong className="text-white">Outputs Based on Available Data.</strong> All Corvus outputs — including Verdicts, Reckonings, scores, alerts, and recommendations — are based solely on data submitted by the customer and the conditions observable from that data. OCWS does not independently verify environmental conditions, network infrastructure, or hardware beyond what is visible in submitted screenshots and declared information.
              </p>
              <p>
                <strong className="text-white">Services Provided &ldquo;As Is.&rdquo;</strong> Except as expressly stated in the Guarantee Policy, all Services are provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranty of any kind, express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement.
              </p>
            </div>
          </div>

          {/* 6. User Responsibilities */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">6. Customer Responsibilities</h2>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <p><strong className="text-white">Data Accuracy.</strong> You are responsible for submitting accurate, complete, and unmodified scanner data, screenshots, and environmental information. Manipulated or misrepresented data will produce unreliable outputs, and OCWS bears no responsibility for the accuracy of results derived from inaccurate inputs.</p>
              <p><strong className="text-white">Implementation Decisions.</strong> You are solely responsible for all decisions made in reliance on Corvus outputs or any other OCWS advisory content. OCWS recommendations do not constitute professional engineering advice, and you should consult qualified professionals before making significant network infrastructure decisions.</p>
              <p><strong className="text-white">Account Security.</strong> You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. Notify OCWS immediately of any unauthorized use.</p>
              <p><strong className="text-white">Compliance.</strong> You are responsible for ensuring your use of OCWS Services complies with all applicable laws, regulations, and third-party agreements, including but not limited to ISP terms of service and workplace IT policies.</p>
            </div>
          </div>

          {/* 7. Acceptable Use */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">7. Acceptable Use</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: "#aaa" }}>
              You agree not to use Corvus, Crow&rsquo;s Eye, or any other OCWS product or service to:
            </p>
            <ul className="space-y-2 text-sm" style={{ color: "#aaa" }}>
              {[
                "Analyze networks or RF environments for which you do not have authorization.",
                "Engage in surveillance, interception, or unauthorized monitoring of third-party networks or communications.",
                "Submit false, fabricated, or third-party data without authorization.",
                "Resell, sublicense, or commercially redistribute OCWS outputs without prior written consent.",
                "Reverse engineer, decompile, or attempt to extract OCWS platform logic, scoring methodology, or AI models.",
                "Interfere with or disrupt OCWS systems, infrastructure, or other customers.",
                "Violate any applicable law, regulation, or third-party right.",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span style={{ color: "#00C2C7", flexShrink: 0 }}>—</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </div>

          {/* 8. Intellectual Property */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">8. Intellectual Property</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: "#aaa" }}>
              Corvus, Crow&rsquo;s Eye, The Full Reckoning, and Corvus&rsquo; Verdict are unregistered trademarks of Old Crows Wireless Solutions LLC. All platform logic, scoring systems, diagnostic methodology, AI models, monitoring systems, report templates, and associated intellectual property remain the exclusive property of OCWS.
            </p>
            <p className="text-sm leading-relaxed" style={{ color: "#aaa" }}>
              Your purchase of a Verdict, Reckoning, or other report grants you ownership of the specific output document for personal, internal, or authorized commercial use, subject to the restrictions described in the Report Ownership &amp; Usage Policy. It does not grant any license to OCWS technology, platform, methodology, or intellectual property.
            </p>
          </div>

          {/* 9. Limitation of Liability */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">9. Limitation of Liability</h2>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <p>To the maximum extent permitted by applicable law, Old Crows Wireless Solutions LLC, its members, managers, employees, contractors, and agents shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages arising out of or related to your use of Corvus, Crow&rsquo;s Eye, or any other OCWS product or service, regardless of the theory of liability and even if OCWS has been advised of the possibility of such damages.</p>
              <p>This includes, without limitation, damages for:</p>
              <ul className="space-y-1 ml-4">
                {[
                  "Loss of revenue, profit, data, or business opportunity",
                  "Network downtime or service degradation",
                  "Reliance on OCWS outputs or recommendations",
                  "Security incidents occurring after implementation of OCWS recommendations",
                  "Inaccuracies in outputs due to submitted data limitations",
                ].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span style={{ color: "#00C2C7", flexShrink: 0 }}>—</span>
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p>OCWS&rsquo;s total aggregate liability to you for any claim arising out of or related to these Terms or the Services shall not exceed the total amount paid by you to OCWS in the twelve (12) months preceding the claim.</p>
            </div>
          </div>

          {/* 10. Modifications */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">10. Service Modifications and Availability</h2>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <p>OCWS reserves the right to modify, suspend, or discontinue any aspect of its Services at any time with reasonable notice. Material changes to pricing or plan features will be communicated in advance. Continued use of the Services after notice of changes constitutes acceptance.</p>
              <p>OCWS does not guarantee uninterrupted availability of its platform or Services and is not liable for downtime, maintenance periods, or service interruptions outside its reasonable control.</p>
            </div>
          </div>

          {/* 11. Termination */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">11. Termination</h2>
            <div className="space-y-3 text-sm" style={{ color: "#aaa" }}>
              <p>Either party may terminate a subscription or service agreement in accordance with the applicable plan terms and Refund Policy. OCWS may immediately suspend or terminate your access to Services if you violate these Terms, engage in fraud, or otherwise threaten the integrity of OCWS systems or other customers.</p>
              <p>Upon termination, your right to access the platform ceases. Reports already delivered and paid for remain yours, subject to the Report Ownership &amp; Usage Policy.</p>
            </div>
          </div>

          {/* 12. Governing Law */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid rgba(255,255,255,0.08)" }}>
            <h2 className="text-xl font-bold text-white mb-4">12. Governing Law and Disputes</h2>
            <p className="text-sm leading-relaxed mb-3" style={{ color: "#aaa" }}>
              These Terms are governed by and construed in accordance with the laws of the State of Florida, without regard to its conflict of law provisions. Any disputes arising under or related to these Terms shall be resolved in the courts of Escambia County, Florida, and you consent to personal jurisdiction in that venue.
            </p>
            <p className="text-sm leading-relaxed" style={{ color: "#aaa" }}>
              Before initiating formal legal proceedings, both parties agree to make a good-faith effort to resolve disputes informally by contacting OCWS at the address listed below.
            </p>
          </div>

          {/* 13. Contact */}
          <div className="rounded-2xl p-8" style={{ background: "#1A2332", border: "1px solid #0D6E7A" }}>
            <h2 className="text-xl font-bold text-white mb-4">13. Contact</h2>
            <p className="text-sm leading-relaxed" style={{ color: "#aaa" }}>
              Questions regarding these Terms may be directed to:
            </p>
            <div className="mt-4 text-sm" style={{ color: "#aaa" }}>
              <p className="text-white font-semibold">Old Crows Wireless Solutions LLC</p>
              <p>Pensacola, Florida</p>
              <p className="mt-2">
                <Link href="/contact" className="ocws-glow-hover rounded-lg px-1 -ml-1" style={{ color: "#00C2C7" }}>
                  Contact form &rarr;
                </Link>
              </p>
            </div>
          </div>

          {/* Policy nav */}
          <div className="rounded-2xl p-6" style={{ background: "rgba(0,0,0,0.2)", border: "1px solid rgba(255,255,255,0.06)" }}>
            <p className="text-xs font-semibold uppercase tracking-widest mb-4" style={{ color: "#888" }}>Related Policies</p>
            <div className="flex flex-wrap gap-3">
              {[
                { href: "/legal/guarantee", label: "Guarantee Policy" },
                { href: "/legal/refunds", label: "Refund Policy" },
                { href: "/legal/report-ownership", label: "Report Ownership & Usage" },
              ].map((l) => (
                <Link
                  key={l.href}
                  href={l.href}
                  className="inline-flex items-center rounded-xl px-4 py-2 text-sm font-semibold ocws-glow-hover"
                  style={{ border: "1px solid rgba(0,194,199,0.35)", color: "#00C2C7", background: "transparent" }}
                >
                  {l.label}
                </Link>
              ))}
            </div>
          </div>

        </div>
      </section>
    </main>
  );
}
